name: vet&test
on: [push, pull_request]
jobs:
  check_correctness:
    runs-on: ubuntu-latest
    env:
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: vet
        run: go vet ./...
      - name: test
        run: go test -v ./...